### PR TITLE
amlogic: Fix and enable fastboot flashing flow

### PR DESCRIPTION
**Pull request by rsglobal**

### CODE REVIEW

**Comment by rsglobal** [comment]
Hi @mikegapinski , 

Do you have a chance to test radxa_zero with EMMC? For some reason, my board returns `unable to select a mode : -5` error, so I can't test it myself.

**Comment by mikegapinski** [comment]
@rsglobal Sure! I'll get it tested this week

**Comment by mikegapinski** [comment]
@rsglobal I tested with both EMMC and SD. Flashing works.

Tons of error in the logcat: (bluetooth and mesa, note: I am using headless mode) 

07-18 17:43:24.342  1884  1884 E GBM-MESA-WRAPPER: Unable to create BO, size=1024x768, fmt=875708993
07-18 17:43:24.342  1884  1884 E [minigbm:gbm_mesa_internals.cpp(410)]: Failed to allocate for scanout, trying non-scanout

scrcpy does not start and ADB does not return a serial number:

mgapinski@MacBook-Pro Downloads % scrcpy
scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
ERROR: Device could not be connected (state=serial)
ERROR: Server connection failed
mgapinski@MacBook-Pro Downloads % adb devices
List of devices attached
(no serial number)	device

Right now I have the board ready to go with all Tesla Android patches applied, I'll be trying to fix whatever I can to support this board on my end too. Decoders & encoders would be the first thing I'll focus on when the things I've seen in logs are done

**Comment by mikegapinski** [comment]
One other thing... Radxa Zero has a newer revision that has a different Wi-Fi chip. We need to see if we can support both of if we'll need two rom variants

**Review by mikegapinski — APPROVED** [review]

**Comment by rsglobal** [comment]
@mikegapinski, Thank you for testing.

> E GBM-MESA-WRAPPER: Unable to create BO, size=1024x768, fmt=875708993

This may happen due to missing the CMA region reservation.
I'll check it, and if so - I will fix it in the next PR.

**Comment by mikegapinski** [comment]
> @mikegapinski, Thank you for testing.
> 
> > E GBM-MESA-WRAPPER: Unable to create BO, size=1024x768, fmt=875708993
> 
> This may happen due to missing the CMA region reservation. I'll check it, and if so - I will fix it in the next PR.

Thanks!

I'll try my luck with bringing over some stuff from lineage - they support boards with this SOC since it was used by google in their devkit. Everything works there, but tons of stuff is handled with proprietary blobs like it usually is. I do not consider this a goto solution for things like codecs but I'd rather start with having those things and replacing them with open alternatives. At least that's how I'd approach this in my fork; those changes do not have to be merged here

https://github.com/LineageOS/android_device_amlogic_g12-common

**Pull request merged**
